# -*- coding: utf-8 -*-
"""Aula3_Pandas_Madu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UiBQjUlh-scPWPMukSaG-ZGyW74q2IMx
"""

# Importando a biblioteca Pandas
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/datasets/Gapminder.csv",error_bad_lines=False,delimiter=';')  # pode-se usar tbém sep=';'

# Visualizando as 5 primeiras linhas
df.head()

# 
df.rename(columns={"country": "País","lifeExp": "Expectativa de Vida", "gdpPercap": "PIB"})

df = df.rename(columns={"pop":"População","continent": "Continente","country": "País","lifeExp": "Expectativa de Vida", "gdpPercap": "PIB","year": "Ano"})

df

#Total de linhas e colunas
df.shape

df.columns

df.dtypes

df.tail(15)

df.describe()

# Valores únicos de continente
df["Continente"].unique()

df.tail()

# Cinco primeiras linhas do continente oceania
Oceania = df.loc[df["Continente"] == "Oceania"]
Oceania.head()

# Informações estatísticas 
df.describe()

# Quantidade de países por continente
df.groupby("Continente")["País"].nunique()

# Média de Expectitativa de Vida por Ano
df.groupby("Ano")["Expectativa de Vida"].mean()

# Média PIB
df["PIB"].mean()

# Total PIB
df["PIB"].sum()

# Média de Expectitativa de Vida por País
df.groupby("País")["Expectativa de Vida"].mean()

# Expectativa de Vida no Brazil por Ano
Brazil = df.loc[df["País"] == "Brazil"]
Brazil.groupby("Ano")["Expectativa de Vida"].mean()